### PR TITLE
Added Webassembly support

### PR DESCRIPTION
**Pull request by FabianGoettl**
Hello,
to build a Webassembly binary please use the added BUILD_WASM option in cmake.

For the original asm.js version I had to use the "-s ALLOW_MEMORY_GROWTH=1" flag, otherwise the program was running slower with the optimizations turned on. I am on the recent Emscripten version 1.37.22.

Thanks for your amazing work!

### CODE REVIEW

**Comment by adishavit** [comment]
This is great! Thanks!
So glad you could patch it up for WASM support.

What is `docs_wasm/server.js`?
Can you explain a bit more about the SSE support. I did try to get that work - but got some linking problems and had to disable it, Is it now enabled for the OpenCV build too?

(I got a busy week, but I'll try to run this on my side asap.)

**Comment by FabianGoettl** [comment]
For SSE support make sure that CPU_BASELINE and CPU_DISPATCH in cmake are both set to SSE. Additionally you have to add -msse to your OpenCV build AND the Webassembly build.

I just had linking problems with SSE2 and above, but this might gets fixed in future Emscripten versions. Note that Emscripten emulates some SSE functions, which might not improve or even worsen the performance.

Server.js runs a nodejs webserver in the local directory.

**Comment by adishavit** [comment]
I'll only get around to testing this next week - so bear with me.
Could you add step-by-step instructions for node.js to readme?

**Comment by FabianGoettl** [comment]
The server script was unnecessary, so i removed it.

**Comment by adishavit** [comment]
You seem to be way more proficient than me with web-technologies.
Why the web workers?

**Comment by FabianGoettl** [comment]
Web workers enable kind of multi-threading in browsers. Now, the wasm runs its own worker and is on a different thread than the DOM.

**Pull request merged**
